# ===============
# Header
# ===============
# Navigation menu
menu:
  Home: /
  Archives: /archives
  关于: /about/me
  友链: /about/frs

# ===============
# Content
# ===============
# "Read More" link at the bottom of excerpted articles. `false` to hide the link.
excerpt_link: 阅读更多